# Use an Ubuntu image as the base
FROM ubuntu:22.04

# Install Node.js, Python, and pip
RUN apt-get update && \
    apt-get install -y \
    nodejs \
    npm \
    git \
    python3 \
    python3-pip \
    wget \
    python3-venv \
    python-is-python3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Node.js using n
RUN npm install -g n && \
    n 20.0.0

# Add this repo as safe
RUN git config --global --add safe.directory /workspaces/BarterDB

# Set the working dir
WORKDIR /workspaces/BarterDB
